variable "resource_group_name" {
  type        = string
  description = "Name of the existing KodeKloud-provided resource group. This module never creates a resource group (docs/decisions.md ADR-001)."
}

variable "prefix" {
  type        = string
  description = "Short lowercase alphanumeric prefix used to build the globally-unique server name (\"psql-\" + prefix + \"-\" + 6-char suffix). Must match the value used across all modules."

  validation {
    condition     = can(regex("^[a-z0-9]{3,11}$", var.prefix))
    error_message = "prefix must be 3-11 lowercase letters/digits."
  }
}

variable "location" {
  type        = string
  description = "Azure region. KodeKloud only permits eastus, westus, centralus, or southcentralus. This project standardizes on eastus."
  default     = "eastus"
}

variable "postgresql_version" {
  type        = string
  description = "PostgreSQL major version to deploy. 16 is the current Azure-supported GA release. Valid values: \"11\", \"12\", \"13\", \"14\", \"15\", \"16\"."
  default     = "16"

  validation {
    condition     = contains(["11", "12", "13", "14", "15", "16"], var.postgresql_version)
    error_message = "postgresql_version must be one of: 11, 12, 13, 14, 15, 16."
  }
}

variable "administrator_login" {
  type        = string
  description = "Username for the PostgreSQL server admin account. Cannot be \"azure_superuser\", \"azure_pg_admin\", \"admin\", \"administrator\", \"root\", \"guest\", or \"public\"."
  default     = "pgadmin"

  validation {
    condition = !contains(
      ["azure_superuser", "azure_pg_admin", "admin", "administrator", "root", "guest", "public"],
      var.administrator_login
    )
    error_message = "administrator_login uses a reserved Azure PostgreSQL username. Choose a different value."
  }
}

variable "administrator_password" {
  type        = string
  sensitive   = true
  description = "Password for the PostgreSQL admin account. Supplied from Key Vault via the root module (generated by random_password). Marked sensitive — never appears in plan/apply terminal output."
}

variable "sku_name" {
  type        = string
  description = "Compute SKU for the server. Format: \"<tier>_<vm_sku>\". KodeKloud requires the Burstable tier (prefix \"B_\") with Standard_B1ms or Standard_B2s. B_Standard_B1ms (1 vCPU / 2 GiB) is sufficient for the sample app database."
  default     = "B_Standard_B1ms"

  validation {
    condition     = contains(["B_Standard_B1ms", "B_Standard_B2s", "B_Standard_B2ms"], var.sku_name)
    error_message = "KodeKloud only permits Burstable tier SKUs: B_Standard_B1ms, B_Standard_B2s, or B_Standard_B2ms."
  }
}

variable "storage_mb" {
  type        = number
  description = "Allocated storage in megabytes. KodeKloud caps disk at 32 GB (32768 MB). The PostgreSQL Flexible Server minimum is also 32768 MB, making 32768 the only valid value under KK constraints."
  default     = 32768

  validation {
    condition     = var.storage_mb == 32768
    error_message = "storage_mb must be exactly 32768 (32 GB) on KodeKloud: the playground storage cap is ≤32 GB and the Flexible Server minimum is also 32 GB."
  }
}

variable "backup_retention_days" {
  type        = number
  description = "Number of days to retain point-in-time restore backups. KodeKloud caps this at 7. Azure minimum is 1, maximum is 35."
  default     = 7

  validation {
    condition     = var.backup_retention_days >= 1 && var.backup_retention_days <= 7
    error_message = "backup_retention_days must be 1–7 on KodeKloud (playground cap)."
  }
}

variable "database_name" {
  type        = string
  description = "Name of the application database created inside the server. The sample app connects to this database. Cannot be \"postgres\", \"azure_maintenance\", \"azure_sys\", or \"template0\"/\"template1\"."
  default     = "appdb"
}

variable "tags" {
  type        = map(string)
  description = "Common resource tags applied to every resource created by this module."
  default     = {}
}
