variable "resource_group_name" {
  type        = string
  description = "Name of the existing KodeKloud-provided resource group. This module never creates a resource group (docs/decisions.md ADR-001)."
}

variable "prefix" {
  type        = string
  description = "Short lowercase alphanumeric prefix used to build the globally-unique Key Vault name (\"kv\" + prefix + 6-char random suffix). Must be the same value used across all modules."

  validation {
    condition     = can(regex("^[a-z0-9]{3,11}$", var.prefix))
    error_message = "prefix must be 3-11 lowercase letters/digits."
  }
}

variable "location" {
  type        = string
  description = "Azure region. KodeKloud only permits eastus, westus, centralus, or southcentralus. This project standardizes on eastus."
  default     = "eastus"
}

variable "tenant_id" {
  type        = string
  description = "Azure Active Directory tenant ID. Required by Key Vault to authenticate access policies. Retrieved via data.azurerm_client_config.current.tenant_id in the root module."
}

variable "object_id" {
  type        = string
  description = "Object ID of the service principal or user running Terraform. Granted full secret permissions so Terraform can write and later read back all secrets. Retrieved via data.azurerm_client_config.current.object_id in the root module."
}

variable "acr_username" {
  type        = string
  description = "ACR admin username from module.acr.admin_username. Stored as the 'acr-username' secret in Key Vault so Jenkins can pull images without embedding credentials in Jenkinsfiles."
}

variable "acr_password" {
  type        = string
  sensitive   = true
  description = "ACR admin password from module.acr.admin_password. Stored as the 'acr-password' secret. Marked sensitive — never appears in plan/apply terminal output."
}

variable "jenkins_admin_password" {
  type        = string
  sensitive   = true
  description = "Password for the Jenkins built-in admin account. Generated by random_password in the root module and stored here. JCasC reads it at startup via the JENKINS_ADMIN_PASSWORD env var injected from the K8s secret created in terraform/k8s-post/."
}

variable "postgresql_password" {
  type        = string
  sensitive   = true
  description = "Password for the PostgreSQL Flexible Server admin account. Generated by random_password in the root module and stored here. Retrieved by terraform/k8s-post/ to create the app DB secret."
}

variable "tags" {
  type        = map(string)
  description = "Common resource tags applied to every resource created by this module."
  default     = {}
}
